# MNE-CPP Travis CI for Linux and OS-X
language: cpp

env:
  global:
    - secure: O7DzRo9YOK8YR/gNhVrYKZjOVTscbZI5WhSzNWl+PX8y+fFYBJ8z6s4SMC+NfOw1rK7DOXPbHbaVLFRmSHpBoQGzfbAtfgEOzVpdvSmZQCAr8wbYXatuSCr0X1DYLcVwjS2Nss+HUvcwUo7/UqF2Cc66Pa0E5U04RQDgxP3eff8=
    - secure: cAytNukotDedba2rLMckeEc0Pa9vIRPI9Yb9nLjWno5f1XNAfOkV/047KH+UNxZlzWpjYDYx8ni+D40bZya8118LXv1Xnv4VS0QkUGGOQfPz4squ9wOXhmqJDfYQawS34U1w4rfGy73SBhr4g9qTDJwhErtY4+DUntnemK7xssM=
# Doc
    - secure: R2uq/PNfvDjOf0wJwL43d6ApJdc+UMh27vlNCp6W4DZVF3sjghF2vBqQZezFzrQIqPvmY+yEzjwsezPaq4ajUgrGCmMa2WewEf+ZLDOQL5W2PU2ie4h9vfkgm9fYxv1W4l10c52lH14YoGIJ9v1oobTlKLkqBVGXsmQPibiIGis=
    - secure: LRW0C9LXDSl8nXT1BA09yybSSuBViJUDmuFzdHZiuF7dv+wHkFIWdTfQs3TVbIzeOKA5GXqMpTnL/fUBP13N/DW90CgWYG3AO3FsSeqpMEfSNnjV/1+PpjhOd7UMRVxM858PQvDWkbOoqHWrX1K7fIPiEDadaXLHAYT/IvRuFQM=
# Master
    - secure: UNVlG2ziFsPVZinunXZe2z+XRPJpYOunT03gh9zLmsZlqQiBMNFaONrR4poyybvN9VpyduPjA/IXytVKWAkUdUplDQVz6YRq8Cz21fMeWzDEN37O8fSZiV9av/mQb6hVUFFE1BoRREAbxnsY8mYvClLVHDCJ1eqZPzI4ygZNPRU=
    - secure: XkDdJxkMoatuX5VCInBBMUnmc3DitqjMfh2jyoPTy6oGDGlXMwScp2XhyWiap5pUpEEZ4Kw6MRupNPFbGmWW+d8qx8W5b43K2qjXwSFqw/EmvGxljhtnhnPrRM02JwDRisYP7aU5lFnfg/meyLH5pH2Gx1vGdOLclu6xeojepbs=
# 1.0.0
    - secure: YXurlzTjVZYR8t3W9K7rcFLCnpR7DerHQ15hgojGrCthKlkLuMy7maDrVx4Xq+KFuNmFzEZavla+GKdx5E+EhmZtaSx5OFfejfI1ya5WNTjwQgL5niQV4HoTCKNHZhwIovIEYkyLSaIPZbfccfXBRFegMrBQpVsSSBQoKZiUFfk=
    - secure: bQ7qDeGFDGiYIpudj50F+AXQkwi6HqBPmnrBEJ8DxAkYOy2evBxvACigUM+kx78LM1idOl+njye5HAtlLN8ZiQKikt9YSUXlxbX5es/wk0ABUZ/icWgsbiPU+ThHTNeP4mu33HW8o/vuoKARbaSjkOWn5RejGoiJKNDdnkgJTHw=

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: BUILD=linux_release
    - os: osx
      osx_image: xcode8
      compiler: clang
      env: BUILD=osx_release
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: BUILD=linux_minimal
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: BUILD=linux_tests
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: BUILD=documentation
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: BUILD=coverity
  allow_failures:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: BUILD=coverity

before_install: . tools/travis/$BUILD/before_install.sh
install: . tools/travis/$BUILD/install.sh
before_script: . tools/travis/$BUILD/before_script.sh
script: bash -x tools/travis/$BUILD/script.sh
after_success: . tools/travis/$BUILD/after_success.sh

notifications:
  email:
    - christoph.dinh@mne-cpp.org
    - lorenz.esch@mne-cpp.org
