# MNE-CPP AppVeyor CI for Windows

version: 1.0.0-{build}

os: Visual Studio 2015
platform: x64
configuration:
    - windows_release
    - windows_tests

init:
    - ps: if($env:APPVEYOR_PULL_REQUEST_TITLE) { $env:is_not_pr = "true"; }

install:
    - echo %APPVEYOR_PULL_REQUEST_TITLE%
    - echo %is_not_pr%
    - set QTDIR=C:\Qt\5.7\msvc2015_64
    - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin;C:\Qt\QtIFW2.0.1\bin
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

build:
  parallel: true
  #quiet|minimal|normal|detailed
  verbosity: detailed 

before_build:
    - call .\tools\appveyor\%CONFIGURATION%\before_build.bat
build_script:
    - call .\tools\appveyor\%CONFIGURATION%\build.bat
after_build:
    - call .\tools\appveyor\%CONFIGURATION%\after_build.bat

before_test:
    - call .\tools\appveyor\%CONFIGURATION%\before_test.bat
test_script:
    - call .\tools\appveyor\%CONFIGURATION%\test.bat

artifacts:
  - path: mne-cpp-windows-x86_64-$(APPVEYOR_REPO_BRANCH).exe
    name: installer
  - path: mne-cpp-windows-x86_64-$(APPVEYOR_REPO_BRANCH).zip
    name: bin_archive

deploy:
  # master
  - provider: FTP
    protocol: ftp
    host:
      secure: ckK4+pPybTYYRiKxXpZScwZlxRmpxUgTvZaTN+vVAfU=
    username:
      secure: aUqYXjXjd4dh3sO18+x8qw==
    password:
      secure: u8DCGb7s6kuPyjybX/THWFQ0VMCfpLD5IsB/9nzGnvk=
    artifact: installer,bin_archive
    on:
      branch: master
      configuration: windows_release
      is_not_pr: true

  # 1.0.0
  - provider: FTP
    protocol: ftp
    host:
      secure: ckK4+pPybTYYRiKxXpZScwZlxRmpxUgTvZaTN+vVAfU=
    username:
      secure: OjcVi/WSo4rGcclzEOQCEw==
    password:
      secure: 8mgxeu0zEr2vEble0FcDE0BlVbw+4zo1j+J4QigGUvk=
    artifact: installer,bin_archive
    on:
      branch: 1.0.0
      configuration: windows_release
      is_not_pr: true

notifications: 
  - provider: Email 
    to: 
      - christoph.dinh@mne-cpp.org
      - lorenz.esch@mne-cpp.org
    on_build_status_changed: true
