# MNE-CPP AppVeyor CI for Windows

version: 1.0.0-{build} 
pull_requests:
  do_not_increment_build_number: true

os: Visual Studio 2015
platform: x64
configuration: Release

build:
  parallel: true
  #quiet|minimal|normal|detailed
  verbosity: normal 
  
cache: 
    - C:\projects\mne-cpp_shadow_build\MNE
    - C:\projects\mne-cpp_shadow_build\testframes
    - C:\projects\mne-cpp_shadow_build\examples
    - C:\projects\mne-cpp_shadow_build\applications
   
install:
    - set QTDIR=C:\Qt\5.6\msvc2015_64
    - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

before_build:
    - cd ..
    - if not exist "mne-cpp_shadow_build" mkdir mne-cpp_shadow_build
    - cd mne-cpp_shadow_build
    - qmake ../mne-cpp/mne-cpp.pro -r

build_script:
    - jom

notifications: 
  - provider: Email 
    to: 
      - christoph.dinh@mne-cpp.org
      - lorenz.esch@mne-cpp.org
    on_build_status_changed: true 