name: Coverity
on:
  schedule:
  - cron: '0 0 * * 1,3,5'

jobs:
  ScanLinux:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install Python 3.7 version
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.10.1
          modules: qtcharts
      - name: Coverity scripts
        run: |
          COVERITY_SCAN_PROJECT_NAME="mne-tools/mne-cpp"
          COVERITY_SCAN_NOTIFICATION_EMAIL="mne_cpp@googlegroups.com"
          COVERITY_SCAN_BRANCH_PATTERN="main"
          COVERITY_SCAN_BUILD_COMMAND_PREPEND="cmake -B build -S src -DCMAKE_BUILD_TYPE=Release
          COVERITY_SCAN_BUILD_COMMAND="make -j4"
          COVERITY_SCAN_TOKEN=$COVTOKEN
          PLATFORM=`uname`
          TOOL_ARCHIVE=/tmp/cov-analysis-${PLATFORM}.tgz
          TOOL_URL=https://scan.coverity.com/download/${PLATFORM}
          TOOL_BASE=/tmp/coverity-scan-analysis
          UPLOAD_URL="https://scan.coverity.com/builds?project=mne-tools%2Fmne-cpp"
          SCAN_URL="https://scan.coverity.com"
          wget -nv -O $TOOL_ARCHIVE $TOOL_URL --post-data "project=$COVERITY_SCAN_PROJECT_NAME&token=$COVERITY_SCAN_TOKEN"
          mkdir -p $TOOL_BASE
          pushd $TOOL_BASE
          tar xzf $TOOL_ARCHIVE --warning=none
          popd
          TOOL_DIR=`find $TOOL_BASE -type d -name 'cov-analysis*'`
          export PATH=$TOOL_DIR/bin:$PATH
          echo -e "echo 3"
          echo -e "\033[33;1mRunning Coverity Scan Analysis Tool...\033[0m"
          COV_BUILD_OPTIONS=""
          RESULTS_DIR="cov-int"
          eval "${COVERITY_SCAN_BUILD_COMMAND_PREPEND}"
          COVERITY_UNSUPPORTED=1 cov-build --dir $RESULTS_DIR $COV_BUILD_OPTIONS $COVERITY_SCAN_BUILD_COMMAND
          cov-import-scm --dir $RESULTS_DIR --scm git --log $RESULTS_DIR/scm_log.txt 2>&1
          RESULTS_ARCHIVE=analysis-results.tgz
          tar czf $RESULTS_ARCHIVE $RESULTS_DIR
          SHA=`git rev-parse --short HEAD`
          response=$(curl \
            --silent --write-out "\n%{http_code}\n" \
            --form token=$COVERITY_SCAN_TOKEN \
            --form email=$COVERITY_SCAN_NOTIFICATION_EMAIL \
            --form file=@$RESULTS_ARCHIVE \
            --form version=$SHA \
            --form description="Github Actions build" \
            $UPLOAD_URL)
          echo "$response"
          status_code=$(echo "$response" | sed -n '$p')
        env:
          COVTOKEN: ${{ secrets.COVERITY_TOKEN }}
